language: python
sudo: false
env:
  - TOXENV=py27
  - TOXENV=pypy
#  - TOXENV=py33
#  - TOXENV=py34
#  - TOXENV=py35
#  - TOXENV=pypy3

install:
 - pip install tox
 - pip install coveralls

script:
  - tox

after_success:
  - coveralls
